### ISSUE TITLE
I can see a list of all my events

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#1]
## Value Proposition
​
**As a** User
**I want to** see a list of all my events
**so that** I can remember when my next event is.
​
## Description

![Image](https://user-images.githubusercontent.com/12039112/201699035-f5711dfe-fdb7-485a-9b2e-b87408af5370.png)

## Acceptance Criteria

- [x] all events are displayed in a list
- [x] the list should have it's own headline
- [x] sorted by date
- [x] the list displays the title, date, time and team name

## Tasks

- [x] create dummy data (.json file)
- [x] create a `EventCard` component
  - [x] name, date, time and teamName as prop
  - [x] name, date and time are always required
  - [x] should have a component test
  - [x] should have a storybook story
 - [x] fetch the dummy data and display it in a list

## Complexity
M
