### ISSUE TITLE
I can assign players to a different category

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#13]
## Value Proposition

**As a** User
**I want to** assign players to a category
**so that** I can remember who is attending the event 
​

## Description

<img width="201" alt="image" src="https://user-images.githubusercontent.com/12039112/203338846-c1ab060a-f699-41e2-b155-e01b1c7d4cb3.png">

## Acceptance Criteria

- [x] The player cards have buttons to assign them to the categories accepted or cancelled
- [x] When clicking one of the buttons the player is displayed in the according list
- [x] players can be set back to unassigned
- [x] The category shows how many players are assigned to it​

## Tasks

- [x] create "AssignButton" Component
- [x] add a assignedTo prop to the player
- [x] render the player list depending on the assignedTo prop
- [x] show the list length next to the category
      ​

## Complexity
M

**Comment by FelineHuhn** [comment]
Everything fine in my opinion 👍
