### ISSUE TITLE
The event displays the attendance status in the event list

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#14]
## Value Proposition

**As a** User 
**I want to** see the attendance status in the event list
**so that** I don't have to open every single event
​

## Description

<img width="199" alt="image" src="https://user-images.githubusercontent.com/12039112/203340351-9f324fd5-20fa-4e68-b343-6e06079bf3dd.png">

## Acceptance Criteria

- [x] The number of accepted and cancelled players is displayed on the event card
      ​

## Tasks

- [x] give the EventCard the props "accepted" and "cancelled"
  - [x] should be states so the number is updated onChange
- [x] display the number of accepted and cancelled players on the card
      ​

## Complexity
S
