### ISSUE TITLE
App styling

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#19]
## Value Proposition

**As a** User
**I want** the app to look good  
**so that** I enjoy using it
​

## Description

Make the app look pretty
​

## Acceptance Criteria

- [ ] the style should be mobile first (iPhone SE)
- [ ] the accessibility should be considered
      ​

## Tasks

- [ ] use styled components
- [ ] maybe create some extra styled component files
      ​

## Complexity
S
