### ISSUE TITLE
I can add new events

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#2]
## Value Proposition
​
**As a** User
**I want to** be able to add new events
**so that** I can plan into the future 
​
## Description

![image](https://user-images.githubusercontent.com/12039112/201891258-e90c6820-5a14-4a9b-8042-cc4a309babf5.png)

## Acceptance Criteria

- [x] an add button on the events page leads to an new event form.
- [x] in the new event form event data can be inserted.
- [x] the name, date and time are required inputs, location and description is optional.
- [x] the submit button adds the event to the event list.
- [x] after the submit the user gets redirected to the event list.
- [x] there is a back button to go back to the event page.

## Tasks

- [x] add an add-button on the event list page.
- [x] create new event page.
- [x] link add button with the new event page.
- [x] create an form component for the create page.
- [x] write a function that handles the submit and adds it to the event list.

## Complexity
M
