### ISSUE TITLE
Player Detail

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#20]
## Value Proposition

**As a** User
**I want to** see details about the player
**so that** so that I don't have to remember all information
​

## Description

![image](https://user-images.githubusercontent.com/12039112/204486771-01edb871-cbc0-4b08-8b00-fa5dcfc8fba8.png)
​

## Acceptance Criteria

- [ ] the player card is clickable
- [ ] clicking the player card sends the user to the details page
- [ ] the details page displays all information about the player
- [ ]  clicking on the back button redirects the user back to the event list
      ​

## Tasks

- [ ] turn the card into a link component
- [ ] create player details page
- [ ] link the card with the player details page
- [ ] add a back button that links back to the team page
      ​

## Complexity
S

**Comment by FelineHuhn** [comment]
little typo in the value proposition: "so that" is double, otherwise perfect understandable

**Comment by HendrikNeuschulz** [comment]
top job !
