### ISSUE TITLE
I can add new players

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#21]
## Value Proposition

**As a** User
**I want to** add new players
**so that** I can manage my squad
​

## Description

![image](https://user-images.githubusercontent.com/12039112/204489397-edfaddc8-e970-4a20-94c2-5d96471e7416.png)
​
## Acceptance Criteria

- [x] an add button on the team page leads to a new player form.
- [x] in the new player form player data can be inserted
- [x] the name is a required input the rest is optional.
- [x] the submit button adds the player to the player list.
- [x] after the submit the user gets redirected to the team page.
- [x] there is a back button to go back to the team page.​
- [x] the Navbar is highlighting the ‚Team‘ nav button when the user is active on that page

## Tasks

- [x] add an add-button on the team page
- [x] create new player page
- [x] link add button with the new player page
- [x] create a form component for the create page
- [x] write a function that handles the submit and adds it to the player list
      ​

## Complexity
M

**Comment by marialitwa** [comment]
Hej Gai, looks good nice feature :) I’m just seeing a few minor typos:
Acceptance criteria: 
_a new_ player form, not an
required _input_, not inputs

Tasks:
Create _a form_, not an

Maybe you could add that the Navbar is highlighting the ‚Team‘ nav button when the user is active on that page?
