### ISSUE TITLE
I can edit players

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#22]
## Value Proposition

**As a** User 
**I want to** be able to edit my players
**so that** I can update the player information

## Description

![image](https://user-images.githubusercontent.com/12039112/204489289-4969316a-a6c9-46af-bc95-d387edf99f4e.png)

## Acceptance Criteria

- [x] the player detail page holds an edit button.
- [x] on click, the edit button leads to the player form.
- [x] the player form is pre-filled with the data of the player .
- [x] the data in the form is editable.
- [x] after clicking the submit button, i get redirected to the detail view of the player.
- [x] There is a back button to cancel the edit process.    ​

## Tasks

- [x] add the edit button.
- [x] create a edit page.
- [x] link the edit button to the edit page.
- [x] fill the form with defaultValues.
- [x] write the edit function onSubmit.
- [x] redirect to the details page after the submit.
- [x] add a back button that links to the details page
      ​

## Complexity
M

**Comment by EugenMoser** [comment]
clearly and understandable. Top
