### ISSUE TITLE
I can delete players

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#23]
## Value Proposition

**As a** User
**I want to** be able to delete my players
**so that** players can be removed from the list.

## Description

![image](https://user-images.githubusercontent.com/12039112/204489920-54c50873-c315-4ede-aea3-b603240fc586.png)

## Acceptance Criteria

- [ ] a delete button on the player page prompts a modal which asks if you really want to delete the player. 
- [ ] clicking on yes in the modal deletes the player and redirects you to the team page.
- [ ] clicking on no closes the modal and does not delete the player.
      ​
## Tasks

- [ ] add the delete button
- [ ] create a modal component
- [ ] link the delete button to the modal
- [ ] write the delete function
- [ ] redirect to the team page after the delete​
- [ ] close the modal after click on no

## Complexity
S
