### ISSUE TITLE
Event details page

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#3]
## Value Proposition

**As a** User
**I want to** be able to see all event details  
**so that** I can't forget anything about the event
​ 
## Description

![Image](https://user-images.githubusercontent.com/12039112/201909056-435a980b-6108-4fed-bbc3-01f7219b3576.png)

## Acceptance Criteria

- [x] the event card is clickable
- [x] clicking on the event card sends me to a details page.
- [x] the details page displays all information about the event.
- [x] clicking on the back button redirects the user back to the event list
      ​

## Tasks

- [x] turn the card into a Next/Link component
- [x] create event details page
- [x] link the card with the event details page
- [x] add a back button that links back to the event list page
      ​

## Complexity
S

**Comment by FelineHuhn** [comment]
Looks good to me!

**Comment by ahohnsen** [comment]
Hey Gai,

Please add to your acceptance criteria, how the user can go back from the details page to the event list. 🙂
