### ISSUE TITLE
I can edit events

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#4]
## Value Proposition

**As a** User 
**I want to** be able to edit my events
**so that** I can update the event information

## Description

![image](https://user-images.githubusercontent.com/12039112/201910542-b3bf0a40-a3e1-4217-91fb-f295daa14815.png)

## Acceptance Criteria

- [x] the event detail page holds an edit button.
- [x] on click, the edit button leads to the event form.
- [x] the event form is pre-filled with the data of the event .
- [x] the data in the form is editable.
- [x] after clicking the submit button, i get redirected to the detail view of the event.
- [x] There is a back button to cancel the edit process.    ​

## Tasks

- [x] add the edit button.
- [x] create a edit page.
- [x] link the edit button to the edit page.
- [x] fill the form with defaultValues.
- [x] write the edit function onSubmit.
- [x] redirect to the details page after the submit.
- [x] add a back button that links to the details page
      ​

## Complexity
M

**Comment by EugenMoser** [comment]
looks good to me.
one comment: you could fill the defaultValues in the description image
