### ISSUE TITLE
I can delete events

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#5]
## Value Proposition

**As a** User
**I want to** be able to delete my events
**so that** events can be removed from the list.

## Description

![Image](https://user-images.githubusercontent.com/12039112/201908830-2d749295-da21-46e1-868b-fead3be27d91.png)

## Acceptance Criteria

- [x] a delete button on the event page prompts a modal which asks if you really want to delete the event. 
- [x] clicking on yes in the modal deletes the event and redirects you to the event list.
- [x] clicking on no closes the modal and does not delete the event.
      ​
## Tasks

- [x] add the delete button
- [x] create a modal component
- [x] link the delete button to the modal
- [x] write the delete function
- [x] redirect to the event list after the delete​
- [x] close the modal after click on no

## Complexity
M
