### ISSUE TITLE
I can see a list of players of my team

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#6]
## Value Proposition

**As a** User
**I want to** see a list of players
**so that** I know who belongs to my team​

## Description

![image](https://user-images.githubusercontent.com/12039112/201936260-7fe12e24-0060-4b53-9008-8cc9f623cbef.png)

## Acceptance Criteria

- [x] the user has a navigation to navigate between the events and the team page
- [x] the user can navigate to the team page which will show all players and some information about the team
- [x] all players who are on that team are displayed in a list
- [x] the list should have it's own headline      ​

## Tasks

- [x] create a `PlayerCard` component
- [x] the card has name, position, age and special role as prop
- [x] name and age are always required, position and special role are optional
- [x] should have a component test and a storybook story
      ​

## Complexity
S
