### ISSUE TITLE
The players are displayed in the event

### ISSUE THREAD

**Issue by gaiisay** [gaiisay/capstone-project#7]
## Value Proposition

**As a** User
**I want to** see the players in my events
**so that** I know who is attending
​

## Description

![image](https://user-images.githubusercontent.com/12039112/203507384-8fbd0bd8-f31b-445b-9349-a951a9135c70.png)

## Acceptance Criteria

- [x] the event has the attendance category unassigned
- [x] the players are initially displayed in the unassigned category
- [x] the player card only shows the picture and name

## Tasks

- [x] create attendance categories (as lists)
- [x] display the players under unassigned
- [x] make the player card display less info

## Complexity
S
